version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - add_ssh_keys:
          fingerprints:
            - "57:69:ac:a3:37:79:a9:74:9d:da:53:8b:07:99:49:2a"
      - run:
          name: Update
          command: |
              ssh -o StrictHostKeyChecking=no git@github.com || true
              git clone git@github.com:ylemkimon/circleci-test.git ctest
              cd ctest
              echo 'test' > TEST.md
              git add TEST.md
              git commit -m "test"
              git push
