version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - build:
          filters:
            branches:
              ignore: gh-pages
