version: 2

jobs:
  sayhello:
    description: A job that does very little other than demonstrate what a parameterized job looks like
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    machine: true
    steps:
      - echo "Hello << parameters.saywhat >>"

workflows:
  version: 2
  build:
    jobs:
      - sayhello:
          saywhat: Everyone
