version: 2
jobs:
  test:
    parameters:
      browser:
        type: string
    docker:
      - image: circleci/node:6
    steps:
      - checkout

workflows:
  version: 2
  test:
    jobs:
      - test
