version: 2
jobs:
  test:
    parameters:
      browser:
        type: string
    docker:
      - image: circleci/node:6
      - image: << parameters.browser >>
    steps:
      - checkout
      - date
      - echo << parameters.browser >>

workflows:
  version: 2
  test:
    jobs:
      - test:
          browser: selenium/standalone-chrome:2.48.2
      - test:
          browser: selenium/standalone-firefox:2.48.2
