version: 2.1
jobs:
  test:
    parameters:
      browser:
        type: string
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          command: echo << parameters.browser >>

workflows:
  version: 2.1
  test:
    jobs:
      - test:
          browser: selenium/standalone-chrome:2.48.2
      - test:
          browser: selenium/standalone-firefox:2.48.2
