version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "40:f4:c0:ec:5f:7a:77:9d:4f:db:07:45:05:a6:5e:e1"

workflows:
  version: 2
  test:
    jobs:
      - test
