version: 2.1

executors:
  node6:
    docker:
      - image: circleci/node:6
  node8:
    docker:
      - image: circleci/node:8

jobs:
  test:
    parameters:
      exc:
        type: enum
        enum: ["node6", "node8"]
    executor: << parameters.exc >>
    steps:
      - checkout

workflows:
  version: 2
  test:
    jobs:
      - test:
          exc: node6
      - test:
          exc: node8
